### ISSUE TITLE
Update to Simple-Sensor-SOLDERED needed

### ISSUE THREAD

**Issue by JWBuilds** [SolderedElectronics/Soldered-Simple-Sensor-Arduino-Library#2]
Hi there, 

After running the simple-sensor-soldered library a few months ago with no issues, I now couldn't build my project. I've found the solution but just in case someone else encounters this issue or if the author wishes to update the library, I've detailed below my fix. 

I'm using this library as part of a larger project where I've connected a rain and soil sensor to an ESP32 (Wroom 32). I'm building the code in VSCode using PlatformIO. 

The error I encountered is as follows: 

```
In file included from lib/Simple-Rain-Sensor-SOLDERED/Simple-Rain-Sensor-SOLDERED.h:15,
                 from src/main.cpp:7:
lib/Simple-Sensor-SOLDERED/Simple-Sensor-SOLDERED.h:21:11: error: expected ',' or '...' before numeric constant
 #define R 10000
           ^~~~~
```

I believe this might be linked to an updated of the PlatformIO platform dependencies but just in case someone else encounters this issue, there is an easy fix: 

- rename the `R` variable in `Simple-Sensor-SOLDERED.h` by a longer name (I used `RES`)
- rename the `R` variable in `Simple-Sensor-SOLDERED.cpp` by a longer name (I used `RES`, make sure you use the same variable name as above)

**Comment by AN63L** [comment]
The fix is detailed in the original post.

**Comment by rsoric** [comment]
Hi @AN63L,

great suggestion, I did this exact thing in a push to [dev.](https://github.com/SolderedElectronics/Soldered-Simple-Sensor-Arduino-Library/tree/dev). This library's name still needs to be updated in the Arduino library index and we're doing that in bulk with all our libraries so that will be done at another time.

Seems to compile fine on all boards and it compiled fine on my local machine. 

All the best and thanks for the contribution :)

-Rob
